### ISSUE TITLE
Version 0.9 not available on PyPI

### ISSUE THREAD

**Issue by dstansby** [lincbrain/linc-cli#43]
I just tried uploading a dataset, and got the message:

Upload failed, and you are not using the latest version of lincbrain-cli.  We suggest upgrading lincbrain-cli to v0.9.0 and trying again.

But it looks like v0.9.0 isn't available on PyPI: https://pypi.org/project/lincbrain-cli/#history

**Comment by kabilar** [comment]
Thanks for the report @dstansby.  This is due to our release process being manual at the moment.  @aaronkanzer can you please manually resolve this issue?

**Comment by aaronkanzer** [comment]
@dstansby Can you proceed with `pip install lincbrain-cli==0.8.5` in the meantime? I can look into this error message when I get the chance, but ideally the pinned install to 0.8.5 should unblock you

**Comment by aaronkanzer** [comment]
@kabilar just for reference -- it seems that that error message @dstansby got is just a catch-all for any upload error -- the dandi (lincbrain) CLI rounds up the semantic version in that error message when surfacing to the end user

https://github.com/dandi/dandi-cli/blob/15196a93310618f8897c7b43444e216bbb094549/dandi/upload.py#L444-L460

**Comment by kabilar** [comment]
Hi @dstansby, thanks for the report.  @aaronkanzer has now resolved this error.  The latest release (`0.10.0`) now has a GitHub tag, GitHub release, and PyPi release.
