### ISSUE TITLE
Add some feedback when uploading datasets

### ISSUE THREAD

**Issue by dstansby** [lincbrain/linc-cli#45]
I'm currently uploading a large (300 GB) dataset, or at least I think I am... there's a Python process using my outgoing internet at 200Mbps, but all that the lincbrain cli has told me is:
```
$ lincbrain upload
2024-05-02 15:20:14,885 [    INFO] Found 6 files to consider
```

It would be nice if there was some sort of progress bar, or at a minimum a message saying the CLI was starting a file upload.

**Comment by kabilar** [comment]
Thanks @dstansby.  This is a good idea.  I am going to repost this suggestion to the DANDI Client repo [Issue #400](https://github.com/dandi/dandi-cli/issues/400), since they lead development of the Client.  And I will close this issue.

**Comment by kabilar** [comment]
Once they develop a solution, we will pull those changes into the LINC Client.

cc @aaronkanzer
