### ISSUE TITLE
Package not available on conda forge

### ISSUE THREAD

**Issue by dstansby** [lincbrain/linc-cli#47]
Searching https://conda-forge.org/packages/ it looks like this pacakge isn't on conda-forge, even though the README says it is. Would be good to update the readme to remove mention of conda-forge, or upload to conda-forge.

**Comment by kabilar** [comment]
Thanks @dstansby.  We don't plan on uploading the package to conda-forge.  #46 will update the readme.

**Comment by kabilar** [comment]
Hi @dstansby, the readme is now updated.  Thanks.

**Comment by kabilar** [comment]
Actually #50 is the real fix.
