### ISSUE TITLE
Error trying to upload data

### ISSUE THREAD

**Issue by dstansby** [lincbrain/linc-cli#48]
I'm getting

```
 % lincbrain upload 000005 
2024-07-18 16:09:25,585 [    INFO] Logs saved in /Users/dstansby/Library/Logs/lincbrain-cli/20240718150923Z-14583.log
Error: Server requires schema version 0.6.7; client only supports 0.6.6.  You may need to upgrade dandi and/or dandischema.
```

Migth be related to https://github.com/lincbrain/linc-cli/issues/43? I only have `lincbrain=0.8.5` as that's what's on PyPI, so maybe this issue is already fixed in version 0.9?

**Comment by dstansby** [comment]
Just tried with version 0.9.0, and this is still giving the same error.

**Comment by kabilar** [comment]
Thanks @dstansby. We are currently working on a solution.  Will be fixed today.

**Comment by aaronkanzer** [comment]
@dstansby this has been resolved -- can you run `pip install lincbrain-cli==0.8.6` locally? Thanks for the patience here.
