### ISSUE TITLE
Configure `lincbrain` PyPI releases

### ISSUE THREAD

**Issue by kabilar** [lincbrain/linc-cli#5]
- [x] Update `lincbrain` PyPI releases.  I would suggest removing previous WIP releases, and starting at `0.1.0`.  In future releases, let's only increment the minor version since the `dandi` package has not yet hit 1.0.
- [x] Understand semantic versioning for autorc package releases
- [ ] Update release docs
  - [x] Create labels for semvar bump in GitHub CLI repo
  ```  
  versionLabels: Map(6) {
    'major' => [ 'major' ],
    'minor' => [ 'minor' ],
    'patch' => [ 'patch', 'performance' ],
    'skip' => [ 'skip-release' ],
    'release' => [ 'release' ],
    'none' => [
      'internal',
      'documentation',
      'tests',
      'dependencies',
      'released',
      'prerelease'
    ]
    ```
  - [x] For releases, manually label each pull request with `release` tag and `major`, `minor`, or `patch` label.

**Comment by aaronkanzer** [comment]
Update: Seems there have been some silent errors regarding GitHub CI/CD pushing an updated `.whl` package to PyPI, thus we are currently pushing from a local build via the following steps:

```
Bump the version in setup.py
```
then
```
python3 -m build. # builds `.whl` in `dist/`
```
then
```
twine upload lincbrain_cli-*.whl

# where the username is __token__ and the password is the API Key
```

**Comment by kabilar** [comment]
Hi @aaronkanzer, could you please update https://github.com/dandi/handbook/pull/104 with our understanding of how the releases are handled (some notes on this process are above)?  We can then close this issue.  Thank you.
