### ISSUE TITLE
Create API docs

### ISSUE THREAD

**Issue by kabilar** [lincbrain/linc-cli#52]
Similar to the [DANDI Client API docs](https://dandi.readthedocs.io/en/latest/index.html), create API docs for the LINC Client.

**Comment by kabilar** [comment]
- [ ] Close the [lincbrain-docs readthedocs project](https://lincbrain-docs.readthedocs.io/en/latest/) since it is superseded by https://lincbrain.readthedocs.io/en/latest/

**Comment by kabilar** [comment]
Hi @aaronkanzer, when you have a chance, can you please delete the `lincbrain-docs` readthedocs project?  Thanks.

**Comment by aaronkanzer** [comment]
> Hi @aaronkanzer, when you have a chance, can you please delete the `lincbrain-docs` readthedocs project? Thanks.

@kabilar -- all set here, I deleted the project on readthedocs

**Comment by kabilar** [comment]
Thanks @aaronkanzer.  It looks like https://lincbrain.readthedocs.io is now also not available.  Were the `lincbrain-docs` and `lincbrain` readthedocs projects tied together?

**Comment by kabilar** [comment]
This is now resolved.  Thanks Aaron.
