### ISSUE TITLE
Could not check linc/linc-cli for version updates

### ISSUE THREAD

**Issue by kabilar** [lincbrain/linc-cli#58]
In the LINC Client logs, the following error occurs with version `0.11.0`.

>```2024-08-05T15:21:16-0500 [DEBUG   ] dandi 54544:8265534464 Could not check linc/linc-cli for version updates: 404 Client Error: Not Found for url: https://rig.mit.edu/et/projects/linc/linc-cli```

I think we need to update the text in the url from `linc` to `lincbrain` (https://rig.mit.edu/et/projects/lincbrain/linc-cli).

Thank you.

**Comment by aaronkanzer** [comment]
Thanks for flagging this -- included a `patch` release here: https://github.com/lincbrain/linc-cli/pull/59 (will bump to `0.11.1`) -- I haven't merged it yet

**Comment by kabilar** [comment]
Thank you, Aaron.
